{
 "title": "Hammerspace Dashboard: Drive Usage and Perf",
 "tags": [
  "Hammerspace",
  "drives",
  "storage"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "dsx_drive_exclusion", "label": "DSX Drive Exclusion Regex", "query": "(dm|md|sr).*" },
   { "name": "anvil_drive_exclusion", "label": "Anvil Drive Exclusion Regex", "query": "(dr|dm).*" },
   { "name": "step", "query": "10m" }
  ]
 },
 "panels": [
  {
   "title": "Anvil Drive Capacity: Highest % Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(8, (sum by (node_type, node_id, device) (label_replace(node_filesystem_size_bytes{cluster='${cluster}',fstype='xfs',node_type='anvil'} - node_filesystem_free_bytes{cluster='${cluster}',fstype='xfs',node_type='anvil'}, 'node_id', '$1', 'instance', '([^.]+).*')) / sum by (node_type, node_id, device) (label_replace(node_filesystem_size_bytes{cluster='${cluster}',fstype='xfs',node_type='anvil'}, 'node_id', '$1', 'instance', '([^.]+).*'))) * 100)",
     "legendFormat": "{{node_type}} > {{node_id}} : {{device}}"
    }
   ]
  },
  {
   "title": "DSX Drive Capacity: Highest % Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(8, (sum by (node_type, node_id, device) (label_replace(node_filesystem_size_bytes{cluster='${cluster}',fstype='xfs',node_type='dsx'} - node_filesystem_free_bytes{cluster='${cluster}',fstype='xfs',node_type='dsx'}, 'node_id', '$1', 'instance', '([^.]+).*')) / sum by (node_type, node_id, device) (label_replace(node_filesystem_size_bytes{cluster='${cluster}',fstype='xfs',node_type='dsx'}, 'node_id', '$1', 'instance', '([^.]+).*'))) * 100)",
     "legendFormat": "{{node_type}} > {{node_id}} : {{device}}"
    }
   ]
  },
  {
   "title": "DSX Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "label_join(\n  label_replace(\n    (\n      rate(node_disk_write_time_seconds_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}])\n      /\n      rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}])\n    ),\n    \"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"\n  ), \n  \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX Write IOPS",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_writes_completed_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX Write Throughput",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_written_bytes_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX read Latency",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "label_join(\n  label_replace(\n    (\n      rate(node_disk_read_time_seconds_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}])\n      /\n      rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}])\n    ),\n    \"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"\n  ), \n  \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX Read IOPS",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_reads_completed_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX Read Throughput",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_read_bytes_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "label_join(\n    label_replace(\n      clamp_max(\n        (\n          rate(node_disk_write_time_seconds_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}])\n          /\n          rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}])\n        ),\n        0.005\n      ),\n      \"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"\n    ),\n    \"sort_key\", \" : \", \"instance_num\", \"device\"\n  )",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Write IOPS",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_writes_completed_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "label_join(\n    label_replace(\n      clamp_max(\n        (\n          rate(node_disk_read_time_seconds_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}])\n          /\n          rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}])\n        ),\n        0.01\n      ),\n      \"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"\n    ),\n    \"sort_key\", \" : \", \"instance_num\", \"device\"\n  )",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Write Throughput",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nclamp_max(rate(node_disk_written_bytes_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}]), 10000000),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Read IOPS",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nclamp_max(rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}]), 200),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Read Throughput",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nclamp_max(rate(node_disk_read_bytes_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}]), 2000000),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  }
 ]
}